### ISSUE TITLE
search seems innacurate

### ISSUE THREAD

**Issue by maxwiseman** [yousofalgburi/GamesLink#1]
When I search for the title of a game, even one that I know is in the database, it just doesn't come up anywhere near the top. I think some sort of relevance sorting option is necessary here rather than sorting by popularity. For example, if I search for the first game on the home page, GTFO, I get 26 results. The first one is Wobbly Life. The only common letter there is "O". This makes it very difficult to use the site.

**Comment by yousofalgburi** [comment]
Hi Max! Thank you for the feedback. The current search system was changed from using a 384 embedding for search terms to a 1584 dimensions. The issue is the the current vector db holds the games as 384 dimensions still :/ so there is a miss-match given bad results. A priority for me right now is fixing that.

**Comment by maxwiseman** [comment]
Ohh, you're using a vector DB. That's pretty impressive, I figured you were just using some sort of steam API and something was going wrong with the search api call. I haven't used vector DBs yet. That sounds like a pretty complicated issue, but I'm sure you'll figure something out. Out of curiosity, what type of vector DB are you using? Now that I think about it, maybe that would be helpful for one of my projects.

**Comment by yousofalgburi** [comment]
I'm using Pinecone:) It's great, I highly recommened it. As far as I know they offer a really generous free tier which works great for this project's goal. I originally had a system that split search terms and looked for exact matches but I wanted something a little bit more smart. The search is an item I plan to continue to improve significantly.

**Comment by maxwiseman** [comment]
So do you just store every single game in your Pinecone DB? That seems like a lot to store.

**Comment by yousofalgburi** [comment]
Yup, I store them all in the DB. I thought that it would be slow but I decided to experiment with it and it turned out to be okay speed. I only return top ~25 results at max in most cases.

**Comment by maxwiseman** [comment]
Wow! It's crazy how efficient databases are these days!
